export { default as SignIn } from './signIn';
export { default as SignUp } from './signUp';
export { default as ForgotPassword } from './forgotPassword';
export { default as Terms } from './terms';
export { default as BasicDetail } from './basicDetail';
export { default as EducationDetail } from './educationDetail';
export { default as WorkDetails } from './workDetails';
export { default as Certification } from './certification';
export { default as PasswordOtp } from './passwordOtp';
export { default as ChangePassword } from './changePassword'